services:
  server:
    build: .
    volumes:
      - servervol:/serverdata
    networks:
      - my_shared_network
    ports:
      - "3002:3002"
networks:
  my_shared_network:
    driver: bridge
    external: true
volumes:
  servervol:
