version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - servervol:/serverdata
    networks:
      - app_network
    ports:
      - "3002:3002"

volumes:
  servervol:

networks:
  app_network:
    external: true

